version: '3.8'
services:
  db:
    container_name: pg_container
    build:
      context: .
      dockerfile: posgres-docker.yml
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "wal_level=logical"]

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./postgres/servers.json:/pgadmin4/servers.json

volumes:
  postgres-data: