spring:
  config:
#    import: "optional:configserver:"
    import: "optional:configserver:http://localhost:9900"
  application:
    name: kafka-cloud-dev
  cloud:
    function:
      definition:
      #uppercase;
#       basicConsumer;
#       basicProducer;
#      firstInput|secondInput;
       batch;batchConsumer;
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        basicProducer-out-0:
          destination: cloud-stream
          content-type: application/json
        basicConsumer-in-0:
          destination: cloud-stream
          contentType: application/octet-stream
          consumer:
            batch-mode: true
        uppercase-out-0:
          destination: cloud-stream
        uppercase-in-0:
            destination: cloud-stream
        firstInput|secondInput-in-0:
          destination: cloud-stream
        batch-out-0:
          destination: cloud-stream
          contentType: application/json
        batchConsumer-in-0:
          destination: cloud-stream
          contentType: application/json
          consumer:
            batch-mode: true